sudo: required
services:
  - docker

before_install:
  - docker build -t panos/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true panos/react-test npm test

after_success:
  - docker build -t panos/multi-client ./client
  - docker build -t panos/multi-nginx ./nginx
  - docker build -t panos/multi-server ./server
  - docker build -t panos/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push panos/multi-client
  - docker push panos/multi-nginx
  - docker push panos/multi-server
  - docker push panos/multi-worker